spring:
  main:
    web-application-type: none
  datasource:
    url: jdbc:h2:file:./data/database
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
  h2:
    console:
      enabled: false
      path: /h2